// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAavcT0EF4QntQ_mai1Sqco-M4TfMvmJE',
    appId: '1:547900345321:web:1652d81ae45d735e56d978',
    messagingSenderId: '547900345321',
    projectId: 'agro-comercial',
    authDomain: 'agro-comercial.firebaseapp.com',
    storageBucket: 'agro-comercial.firebasestorage.app',
    measurementId: 'G-YZSX5EEKFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtOlTuVUKQi6cdG38mepLwN-ZPp5ycNdE',
    appId: '1:547900345321:android:3cb02296370771d956d978',
    messagingSenderId: '547900345321',
    projectId: 'agro-comercial',
    storageBucket: 'agro-comercial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFb3XdGXlktwovOQv1GiuAf21i8yd7tY',
    appId: '1:547900345321:ios:b486a533a8f3c86a56d978',
    messagingSenderId: '547900345321',
    projectId: 'agro-comercial',
    storageBucket: 'agro-comercial.firebasestorage.app',
    iosBundleId: 'dev.vinicius.agrocomercil.agroComercial',
  );

}